import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import ConditionalSideBar from "./components/AdminSidebar";
import DataFetching from "../DataFetching";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by Uzma Ahmed",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DataFetching/>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       {children}
       <ConditionalSideBar/>
      </body>
    </html>
  );
}